# Generated by Django 2.1.1 on 2019-09-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(default='', upload_to='')),
                ('price', models.IntegerField()),
                ('category', models.ManyToManyField(blank=True, related_name='products', to='app.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='Mobile',
        ),
        migrations.AddField(
            model_name='article',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='articles', to='app.Product'),
        ),
    ]
